FROM ubuntu:22.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y ubuntu-desktop nvidia-driver-510 && \
    systemctl mask \
        systemd-load-modules \
        NetworkManager \
        NetworkManager-wait-online \
        bluetooth \
        rtkit-daemon && \
    systemctl set-default graphical.target

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
