FROM fedora:latest
LABEL version="1.0"
LABEL description="Fedora GNOME Image made for easy and clean distrohopping"
LABEL xyz.akdev.distrohop.image="fedora-gnome"

COPY entrypoint.sh /entrypoint.sh
RUN dnf install -y @gnome-desktop && \
    systemctl mask \
        systemd-load-modules \
        NetworkManager \
        NetworkManager-wait-online \
        bluetooth \
        rtkit-daemon

RUN dnf install -y passwd sudo \
        https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
        https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
    dnf install -y xorg-x11-drv-nvidia xorg-x11-drv-nvidia-cuda

RUN systemctl set-default graphical.target

ENTRYPOINT [ "/entrypoint.sh" ]
